apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: dotnet60-sample
  namespace: insights-qa
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: dotnet60-sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: dotnet60-sample-
      labels:
        build.appstudio.openshift.io/application: test
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: dotnet60-sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: insights-qa
    spec:
      params:
      - name: git-url
        value: https://github.com/devfile-samples/devfile-sample-dotnet60-basic.git
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:insights-qa-dotnet60-sample-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:0b05a990917f20f82394d02f28841500df23e612
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: dotnet60-sample/$(tt.params.git-revision)
    status: {}
status: {}
